import React, {useEffect, useMemo, useState} from "react";
import axios from "axios";
import {CalendarDays, Users, BookOpen, DoorOpen, Clock3, WandSparkles, Database, Trash2, Settings2, Check, X, FileSpreadsheet, Upload, Lock, Send, RotateCcw, ShieldCheck, BarChart3, Activity, Bell, UserCheck, RefreshCw, Copy, QrCode, History, ClipboardCheck, UserPlus, DollarSign, GraduationCap, Search, ArrowRight, UsersRound} from "lucide-react";
import {API, days, apiName, refId} from "../core/api";
import {Input, Select} from "../components/FormControls";
import {Metric, Progress} from "../components/Metrics";
import {localToday, authRole} from "../core/helpers";

export function Attendance({data,auth,setMessage}){
  const canMark=["ADMIN","SCHEDULER","FACULTY"].includes(auth.role);
  const [date,setDate]=useState(localToday()),[sectionId,setSectionId]=useState(auth.role==="VIEWER"?refId(auth.section):""),[facultyId,setFacultyId]=useState(auth.role==="FACULTY"?refId(auth.faculty):""),[classes,setClasses]=useState([]),[selected,setSelected]=useState(null),[students,setStudents]=useState([]),[activeView,setActiveView]=useState("MARK"),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[studentId,setStudentId]=useState(""),[studentReport,setStudentReport]=useState(null),[sectionReport,setSectionReport]=useState(null),[report,setReport]=useState(null),[from,setFrom]=useState(""),[to,setTo]=useState("");
  async function loadClasses(){setLoading(true);try{const q=new URLSearchParams({date});if(sectionId)q.set("sectionId",sectionId);if(facultyId)q.set("facultyId",facultyId);const r=await axios.get(`${API}/attendance/today?${q}`);setClasses(r.data.classes||[])}catch(e){setMessage(e.response?.data?.message||e.message)}finally{setLoading(false)}}
  useEffect(()=>{loadClasses()},[date,sectionId,facultyId]);
  async function openClass(c){setLoading(true);try{const r=await axios.get(`${API}/attendance/class/${c.timetableEntryId}?date=${date}`);setSelected(r.data.class);setStudents((r.data.students||[]).map(s=>({...s,attendance:{...s.attendance}})));setActiveView("MARK")}catch(e){setMessage(e.response?.data?.message||e.message)}finally{setLoading(false)}}
  function setStatus(id,status){setStudents(a=>a.map(s=>String(s._id)===String(id)?{...s,attendance:{...s.attendance,status}}:s))}
  function markAll(status){setStudents(a=>a.map(s=>({...s,attendance:{...s.attendance,status}})))}
  async function save(){if(!selected)return;setSaving(true);try{const payload={date,timetableEntryId:selected.timetableEntryId,records:students.map(s=>({student:s._id,status:s.attendance?.status||"UNMARKED",remarks:s.attendance?.remarks||""}))};const r=selected.attendance?.id?await axios.put(`${API}/attendance/session/${selected.attendance.id}`,payload):await axios.post(`${API}/attendance/session`,payload);setMessage(r.data?.message||"Attendance saved.");await loadClasses();await openClass(selected)}catch(e){setMessage(e.response?.data?.message||e.message)}finally{setSaving(false)}}
  async function loadStudentReport(){if(!studentId)return;try{setStudentReport((await axios.get(`${API}/attendance/student/${studentId}?${new URLSearchParams({from,to})}`)).data)}catch(e){setMessage(e.response?.data?.message||e.message)}}
  async function loadSectionReport(){if(!sectionId)return setMessage("Select a section first.");try{setSectionReport((await axios.get(`${API}/attendance/section/${sectionId}?${new URLSearchParams({from,to})}`)).data)}catch(e){setMessage(e.response?.data?.message||e.message)}}
  async function loadReport(){try{const q=new URLSearchParams({from,to});if(sectionId)q.set("sectionId",sectionId);if(facultyId)q.set("facultyId",facultyId);setReport((await axios.get(`${API}/attendance/report?${q}`)).data)}catch(e){setMessage(e.response?.data?.message||e.message)}}
  const counts=students.reduce((a,s)=>{const k=s.attendance?.status||"UNMARKED";a[k]=(a[k]||0)+1;return a},{});
  return <div>
    <div className="view-tabs"><button className={`view-tab ${activeView==="MARK"?"active":""}`} onClick={()=>setActiveView("MARK")}>Mark Attendance</button><button className={`view-tab ${activeView==="STUDENT"?"active":""}`} onClick={()=>setActiveView("STUDENT")}>Student Attendance</button><button className={`view-tab ${activeView==="SECTION"?"active":""}`} onClick={()=>setActiveView("SECTION")}>Section Report</button><button className={`view-tab ${activeView==="REPORT"?"active":""}`} onClick={()=>setActiveView("REPORT")}>Attendance Report</button></div>
    {activeView==="MARK"&&<>
      <section className="panel"><div className="panel-head"><div><h3><ClipboardCheck size={17}/> Attendance</h3><p>Select a date and class from the current timetable. Faculty accounts only see their own classes.</p></div><button className="secondary" onClick={loadClasses}><RefreshCw size={15}/> Refresh</button></div><div className="form-grid"><label className="field"><span>Date</span><input type="date" value={date} onChange={e=>{setDate(e.target.value);setSelected(null)}}/></label><Select label="Section" value={sectionId} options={(data.sections||[]).map(s=>[s._id,`${s.program||""} · ${s.semester||""} · ${s.name}`])} onChange={v=>{setSectionId(v);setSelected(null)}}/><Select label="Faculty" value={facultyId} options={(data.faculty||[]).map(f=>[f._id,f.name])} onChange={v=>{setFacultyId(v);setSelected(null)}}/></div></section>
      <section className="panel"><div className="panel-head"><div><h3>Today's Scheduled Classes</h3><p>{date} · {classes.length} class(es)</p></div></div><div className="faculty-class-grid">{classes.map(c=><div className="faculty-class-card" key={c.timetableEntryId}><div className="faculty-class-time"><strong>{c.startTime}</strong><span>{c.endTime}</span><small>{c.section?.name||"Section"}</small></div><div><strong>{c.subject?.name||"Subject"}</strong><div className="muted">{c.faculty?.name||"Faculty"} · {c.room?.name||"Room"}</div><div style={{marginTop:8}}>{c.attendance?<span className="status-badge approved">{c.attendance.counts?.PRESENT||0} Present · {c.attendance.counts?.ABSENT||0} Absent</span>:<span className="status-badge">Not marked</span>}</div><button className="secondary" style={{marginTop:10}} disabled={!canMark} onClick={()=>openClass(c)}>{c.attendance?"Edit Attendance":"Mark Attendance"}</button></div></div>)}{!classes.length&&<div className="empty-state"><h3>No classes for this date</h3><p>Check the selected date, section and faculty filters.</p></div>}</div></section>
      {selected&&<section className="panel"><div className="panel-head"><div><h3>{selected.subject?.name||"Subject"} · {selected.section?.name||"Section"}</h3><p>{date} · {selected.startTime}–{selected.endTime} · {selected.faculty?.name||"Faculty"}</p></div><div className="form-actions"><button className="secondary" onClick={()=>markAll("PRESENT")}>Mark All Present</button><button className="secondary" onClick={()=>markAll("ABSENT")}>Mark All Absent</button><button className="primary" onClick={save} disabled={saving||!canMark}>{saving?"Saving...":"Save Attendance"}</button></div></div><div className="attendance-counts"><span>Present <b>{counts.PRESENT||0}</b></span><span>Absent <b>{counts.ABSENT||0}</b></span><span>Late <b>{counts.LATE||0}</b></span><span>Leave <b>{counts.LEAVE||0}</b></span><span>Unmarked <b>{counts.UNMARKED||0}</b></span></div><div className="table-wrap"><table><thead><tr><th>Roll No</th><th>Admission No</th><th>Student</th><th>Status</th><th>Remarks</th></tr></thead><tbody>{students.map(s=><tr key={s._id}><td>{s.rollNo}</td><td>{s.admissionNo}</td><td><strong>{s.name}</strong></td><td><div style={{display:"flex",gap:5,flexWrap:"wrap"}}>{["PRESENT","ABSENT","LATE","LEAVE"].map(st=><button key={st} className={s.attendance?.status===st?"primary":"secondary"} style={{fontSize:11,padding:"6px 8px"}} onClick={()=>setStatus(s._id,st)}>{st}</button>)}</div></td><td><input value={s.attendance?.remarks||""} onChange={e=>setStudents(a=>a.map(x=>String(x._id)===String(s._id)?{...x,attendance:{...x.attendance,remarks:e.target.value}}:x))} placeholder="Optional"/></td></tr>)}</tbody></table></div></section>}
    </>}
    {activeView==="STUDENT"&&<section className="panel"><div className="panel-head"><div><h3>Student Attendance</h3><p>View attendance history and percentage for an individual student.</p></div></div><div className="form-grid"><Select label="Student" value={studentId} options={(data.students||[]).map(s=>[s._id,`${s.rollNo} · ${s.name}`])} onChange={setStudentId}/><Input label="From" type="date" value={from} onChange={setFrom}/><Input label="To" type="date" value={to} onChange={setTo}/><div className="form-actions"><button className="primary" onClick={loadStudentReport}>View Attendance</button></div></div>{studentReport&&<><div className="cards" style={{marginTop:18}}>{[["Total Classes",studentReport.total],["Attended",studentReport.attended],["Percentage",`${studentReport.percentage}%`],["Absent",studentReport.counts?.ABSENT||0]].map(([n,v])=><div className="card" key={n}><div className="icon"><ClipboardCheck/></div><div><span>{n}</span><strong>{v}</strong></div></div>)}</div><div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Date</th><th>Subject</th><th>Faculty</th><th>Status</th><th>Remarks</th></tr></thead><tbody>{(studentReport.rows||[]).map(r=><tr key={r._id}><td>{r.date}</td><td>{r.subject?.name||""}</td><td>{r.faculty?.name||""}</td><td>{r.record?.status||"UNMARKED"}</td><td>{r.record?.remarks||""}</td></tr>)}</tbody></table></div></>}</section>}
    {activeView==="SECTION"&&<section className="panel"><div className="panel-head"><div><h3>Section Attendance Report</h3><p>Attendance percentage for every active student in a section.</p></div></div><div className="form-grid"><Select label="Section" value={sectionId} options={(data.sections||[]).map(s=>[s._id,`${s.program||""} · ${s.semester||""} · ${s.name}`])} onChange={setSectionId}/><Input label="From" type="date" value={from} onChange={setFrom}/><Input label="To" type="date" value={to} onChange={setTo}/><div className="form-actions"><button className="primary" onClick={loadSectionReport}>Generate Report</button></div></div>{sectionReport&&<div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Roll No</th><th>Student</th><th>Total</th><th>Present</th><th>Absent</th><th>Late</th><th>Leave</th><th>%</th></tr></thead><tbody>{(sectionReport.students||[]).map(r=><tr key={r.student._id}><td>{r.student.rollNo}</td><td>{r.student.name}</td><td>{r.total}</td><td>{r.present}</td><td>{r.absent}</td><td>{r.late}</td><td>{r.leave}</td><td><strong>{r.percentage}%</strong></td></tr>)}</tbody></table></div>}</section>}
    {activeView==="REPORT"&&<section className="panel"><div className="panel-head"><div><h3>Attendance Report</h3><p>Filter submitted attendance sessions and view overall attendance statistics.</p></div></div><div className="form-grid"><Input label="From" type="date" value={from} onChange={setFrom}/><Input label="To" type="date" value={to} onChange={setTo}/><Select label="Section" value={sectionId} options={(data.sections||[]).map(s=>[s._id,`${s.program||""} · ${s.semester||""} · ${s.name}`])} onChange={setSectionId}/><div className="form-actions"><button className="primary" onClick={loadReport}>Run Report</button></div></div>{report&&<><div className="cards" style={{marginTop:18}}>{[["Attendance Classes",report.summary.classes],["Marked Records",report.summary.records],["Attended",report.summary.attended],["Overall %",`${report.summary.percentage}%`]].map(([n,v])=><div className="card" key={n}><div className="icon"><BarChart3/></div><div><span>{n}</span><strong>{v}</strong></div></div>)}</div><div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Date</th><th>Time</th><th>Section</th><th>Subject</th><th>Faculty</th><th>Records</th></tr></thead><tbody>{(report.sessions||[]).map(r=><tr key={r._id}><td>{r.date}</td><td>{r.startTime}–{r.endTime}</td><td>{r.section?.name||""}</td><td>{r.subject?.name||""}</td><td>{r.faculty?.name||""}</td><td>{r.records?.length||0}</td></tr>)}</tbody></table></div></>}</section>}
  </div>
}



export function FeeManagement({data,sessions,auth,setMessage}){
  const [view,setView]=useState("HEADS");
  const [heads,setHeads]=useState([]),[invoices,setInvoices]=useState([]),[payments,setPayments]=useState([]),[report,setReport]=useState(null);
  const [editing,setEditing]=useState(null),[busy,setBusy]=useState(false);
  const [headForm,setHeadForm]=useState({name:"",code:"",program:"",semester:"",amount:"",frequency:"SEMESTER",dueDate:"",description:""});
  const [filters,setFilters]=useState({sessionId:sessions.find(s=>s.active)?._id||"",sectionId:"",status:""});
  const [generate,setGenerate]=useState({sessionId:sessions.find(s=>s.active)?._id||"",sectionId:"",feeHeadId:""});
  const [payment,setPayment]=useState({invoiceId:"",amount:"",mode:"CASH",reference:"",remarks:"",paymentDate:new Date().toISOString().slice(0,10)});
  const [selectedInvoice,setSelectedInvoice]=useState(null);
  const money=v=>`₹${Number(v||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const activeSessions=sessions||[];
  const sectionOptions=(data.sections||[]).map(s=>[s._id,`${s.program||""} · ${s.semester||""} · ${s.name}`]);
  async function loadHeads(){try{const r=await axios.get(`${API}/fees/heads`);setHeads(r.data||[])}catch(e){setMessage(e.response?.data?.message||e.message)}}
  async function loadInvoices(){try{const q=new URLSearchParams();if(filters.sessionId)q.set("sessionId",filters.sessionId);if(filters.sectionId)q.set("sectionId",filters.sectionId);if(filters.status)q.set("status",filters.status);const r=await axios.get(`${API}/fees/invoices?${q}`);setInvoices(r.data||[])}catch(e){setMessage(e.response?.data?.message||e.message)}}
  async function loadPayments(){try{const r=await axios.get(`${API}/fees/payments`);setPayments(r.data||[])}catch(e){setMessage(e.response?.data?.message||e.message)}}
  async function loadReport(){try{const q=new URLSearchParams();if(filters.sessionId)q.set("sessionId",filters.sessionId);if(filters.sectionId)q.set("sectionId",filters.sectionId);const r=await axios.get(`${API}/fees/reports?${q}`);setReport(r.data)}catch(e){setMessage(e.response?.data?.message||e.message)}}
  useEffect(()=>{loadHeads();loadInvoices();loadPayments()},[]);
  useEffect(()=>{if(filters.sessionId||filters.sectionId||filters.status)loadInvoices()},[filters.sessionId,filters.sectionId,filters.status]);
  function resetHead(){setEditing(null);setHeadForm({name:"",code:"",program:"",semester:"",amount:"",frequency:"SEMESTER",dueDate:"",description:""})}
  function editHead(h){setEditing(h._id);setHeadForm({name:h.name||"",code:h.code||"",program:h.program||"",semester:h.semester||"",amount:h.amount??"",frequency:h.frequency||"SEMESTER",dueDate:h.dueDate?String(h.dueDate).slice(0,10):"",description:h.description||""});setView("HEADS")}
  async function saveHead(){if(!headForm.name||!headForm.code||headForm.amount==="")return setMessage("Fee head name, code and amount are required.");setBusy(true);try{const body={...headForm,amount:Number(headForm.amount),dueDate:headForm.dueDate||null};if(editing)await axios.put(`${API}/fees/heads/${editing}`,body);else await axios.post(`${API}/fees/heads`,body);setMessage(editing?"Fee head updated.":"Fee head created.");resetHead();await loadHeads()}catch(e){setMessage(e.response?.data?.message||e.message)}finally{setBusy(false)}}
  async function generateInvoices(){if(!generate.sessionId||!generate.sectionId||!generate.feeHeadId)return setMessage("Select Academic Session, Section and Fee Head.");setBusy(true);try{const r=await axios.post(`${API}/fees/invoices/generate`,generate);setMessage(r.data.message);await loadInvoices();setView("INVOICES")}catch(e){setMessage(e.response?.data?.message||e.message)}finally{setBusy(false)}}
  async function collectPayment(){if(!payment.invoiceId||!payment.amount)return setMessage("Select an invoice and enter payment amount.");setBusy(true);try{const r=await axios.post(`${API}/fees/payments`,{...payment,amount:Number(payment.amount)});setMessage(r.data.message);setPayment({invoiceId:"",amount:"",mode:"CASH",reference:"",remarks:"",paymentDate:new Date().toISOString().slice(0,10)});await loadInvoices();await loadPayments();setView("PAYMENTS")}catch(e){setMessage(e.response?.data?.message||e.message)}finally{setBusy(false)}}
  async function applyDiscount(inv){const value=window.prompt(`Enter discount for ${inv.invoiceNo}`,String(inv.discount||0));if(value===null)return;try{await axios.post(`${API}/fees/invoices/${inv._id}/discount`,{discount:Number(value)});setMessage("Discount updated.");await loadInvoices()}catch(e){setMessage(e.response?.data?.message||e.message)}}
  const summary=useMemo(()=>{const total=invoices.reduce((n,x)=>n+Number(x.netAmount||0),0),paid=invoices.reduce((n,x)=>n+Number(x.paidAmount||0),0);return {total,paid,balance:Math.max(0,total-paid),overdue:invoices.filter(x=>x.status==="OVERDUE").length}},[invoices]);
  return <div>
    <section className="panel"><div className="panel-head"><div><h3><DollarSign size={17}/> Fee Management</h3><p>Create fee heads, generate student invoices, collect payments and review collection reports.</p></div><span className="status-badge approved">{invoices.length} Invoices</span></div>
      <div className="view-tabs">{[["HEADS","Fee Heads"],["GENERATE","Generate Invoices"],["INVOICES","Invoices"],["PAYMENTS","Collect Payment"],["REPORT","Reports"]].map(([v,l])=><button key={v} className={view===v?"view-tab active":"view-tab"} onClick={()=>setView(v)}>{l}</button>)}</div>
    </section>
    {view==="HEADS"&&<section className="panel"><div className="panel-head"><div><h3>{editing?"Edit Fee Head":"Create Fee Head"}</h3><p>Fee heads can be mapped to a program and semester.</p></div></div><div className="form-grid"><Input label="Fee Name" value={headForm.name} onChange={v=>setHeadForm({...headForm,name:v})}/><Input label="Code" value={headForm.code} onChange={v=>setHeadForm({...headForm,code:v.toUpperCase()})}/><Input label="Program" value={headForm.program} onChange={v=>setHeadForm({...headForm,program:v})}/><Input label="Semester" value={headForm.semester} onChange={v=>setHeadForm({...headForm,semester:v})}/><Input label="Amount" type="number" value={headForm.amount} onChange={v=>setHeadForm({...headForm,amount:v})}/><Select label="Frequency" value={headForm.frequency} options={[["ONE_TIME","One Time"],["SEMESTER","Semester"],["ANNUAL","Annual"],["MONTHLY","Monthly"]]} onChange={v=>setHeadForm({...headForm,frequency:v})}/><Input label="Due Date" type="date" value={headForm.dueDate} onChange={v=>setHeadForm({...headForm,dueDate:v})}/><Input label="Description" value={headForm.description} onChange={v=>setHeadForm({...headForm,description:v})}/></div><div className="form-actions" style={{marginTop:14}}><button className="primary" disabled={busy} onClick={saveHead}>{busy?(editing?"Updating...":"Creating..."):(editing?"Update Fee Head":"+ Add Fee Head")}</button>{editing&&<button className="secondary" onClick={resetHead}>Cancel</button>}</div><div className="table-wrap" style={{marginTop:22}}><table><thead><tr><th>Name</th><th>Code</th><th>Program</th><th>Semester</th><th>Amount</th><th>Frequency</th><th>Due Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{heads.map(h=><tr key={h._id}><td><strong>{h.name}</strong><div className="muted">{h.description}</div></td><td>{h.code}</td><td>{h.program||"All"}</td><td>{h.semester||"All"}</td><td>{money(h.amount)}</td><td>{h.frequency}</td><td>{h.dueDate?String(h.dueDate).slice(0,10):"—"}</td><td>{h.active?<span className="status-badge approved">ACTIVE</span>:"Inactive"}</td><td><button className="secondary" onClick={()=>editHead(h)}>Edit</button></td></tr>)}{!heads.length&&<tr><td colSpan="9">No fee heads created.</td></tr>}</tbody></table></div></section>}
    {view==="GENERATE"&&<section className="panel"><div className="panel-head"><div><h3>Generate Student Invoices</h3><p>One invoice is created for every active student in the selected section. Existing invoices are skipped.</p></div></div><div className="form-grid"><Select label="Academic Session" value={generate.sessionId} options={activeSessions.map(s=>[s._id,s.name])} onChange={v=>setGenerate({...generate,sessionId:v})}/><Select label="Section" value={generate.sectionId} options={sectionOptions} onChange={v=>setGenerate({...generate,sectionId:v})}/><Select label="Fee Head" value={generate.feeHeadId} options={heads.filter(h=>h.active).map(h=>[h._id,`${h.name} · ${money(h.amount)}`])} onChange={v=>setGenerate({...generate,feeHeadId:v})}/></div><div className="message success" style={{marginTop:16}}>Invoices are linked to the selected Academic Session, Section, Student and Fee Head. Duplicate invoices are not created.</div><div className="form-actions" style={{marginTop:14}}><button className="primary" disabled={busy} onClick={generateInvoices}>{busy?"Generating...":"Generate Invoices"}</button></div></section>}
    {view==="INVOICES"&&<section className="panel"><div className="panel-head"><div><h3>Fee Invoices</h3><p>Track billed amount, discounts, payments and outstanding balance.</p></div><button className="secondary" onClick={loadInvoices}><RefreshCw size={15}/> Refresh</button></div><div className="form-grid"><Select label="Academic Session" value={filters.sessionId} options={activeSessions.map(s=>[s._id,s.name])} onChange={v=>setFilters({...filters,sessionId:v})}/><Select label="Section" value={filters.sectionId} options={sectionOptions} onChange={v=>setFilters({...filters,sectionId:v})}/><Select label="Status" value={filters.status} options={[["PENDING","Pending"],["PARTIAL","Partial"],["PAID","Paid"],["OVERDUE","Overdue"]]} onChange={v=>setFilters({...filters,status:v})}/></div><div className="cards" style={{marginTop:18}}>{[["Billed",money(summary.total)],["Collected",money(summary.paid)],["Outstanding",money(summary.balance)],["Overdue",summary.overdue]].map(([n,v])=><div className="card" key={n}><div className="icon"><DollarSign/></div><div><span>{n}</span><strong>{v}</strong></div></div>)}</div><div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Invoice</th><th>Student</th><th>Fee Head</th><th>Session</th><th>Net</th><th>Paid</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>{invoices.map(i=><tr key={i._id}><td><strong>{i.invoiceNo}</strong><div className="muted">Due: {i.dueDate?String(i.dueDate).slice(0,10):"—"}</div></td><td>{i.student?.rollNo} · {i.student?.name}</td><td>{i.feeHead?.name}</td><td>{i.academicSession?.name}</td><td>{money(i.netAmount)}</td><td>{money(i.paidAmount)}</td><td><strong>{money(i.balance)}</strong></td><td><span className={`status-badge ${i.status==="PAID"?"approved":""}`}>{i.status}</span></td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{i.balance>0&&<button className="primary" onClick={()=>{setPayment({...payment,invoiceId:i._id,amount:i.balance});setSelectedInvoice(i);setView("PAYMENTS")}}>Collect</button>}<button className="secondary" onClick={()=>applyDiscount(i)}>Discount</button></div></td></tr>)}{!invoices.length&&<tr><td colSpan="9">No invoices match the selected filters.</td></tr>}</tbody></table></div></section>}
    {view==="PAYMENTS"&&<section className="panel"><div className="panel-head"><div><h3>Collect Fee Payment</h3><p>Record payment against an invoice and generate a receipt number.</p></div></div><div className="form-grid"><Select label="Invoice" value={payment.invoiceId} options={invoices.filter(i=>i.balance>0).map(i=>[i._id,`${i.invoiceNo} · ${i.student?.name||"Student"} · ${money(i.balance)} due`])} onChange={v=>{const i=invoices.find(x=>String(x._id)===String(v));setPayment({...payment,invoiceId:v,amount:i?.balance||""});setSelectedInvoice(i||null)}}/><Input label="Amount" type="number" value={payment.amount} onChange={v=>setPayment({...payment,amount:v})}/><Select label="Payment Mode" value={payment.mode} options={[["CASH","Cash"],["UPI","UPI"],["CARD","Card"],["BANK_TRANSFER","Bank Transfer"],["CHEQUE","Cheque"]]} onChange={v=>setPayment({...payment,mode:v})}/><Input label="Payment Date" type="date" value={payment.paymentDate} onChange={v=>setPayment({...payment,paymentDate:v})}/><Input label="Reference / UTR / Cheque No." value={payment.reference} onChange={v=>setPayment({...payment,reference:v})}/><Input label="Remarks" value={payment.remarks} onChange={v=>setPayment({...payment,remarks:v})}/></div>{selectedInvoice&&<div className="message success" style={{marginTop:14}}>Outstanding for <strong>{selectedInvoice.invoiceNo}</strong>: {money(selectedInvoice.balance)}</div>}<div className="form-actions" style={{marginTop:14}}><button className="primary" disabled={busy} onClick={collectPayment}>{busy?"Saving...":"Collect Payment"}</button></div><div className="table-wrap" style={{marginTop:22}}><table><thead><tr><th>Receipt</th><th>Date</th><th>Student</th><th>Invoice</th><th>Amount</th><th>Mode</th><th>Reference</th></tr></thead><tbody>{payments.slice(0,50).map(p=><tr key={p._id}><td><strong>{p.receiptNo}</strong></td><td>{p.paymentDate?String(p.paymentDate).slice(0,10):""}</td><td>{p.student?.rollNo} · {p.student?.name}</td><td>{p.invoice?.invoiceNo}</td><td>{money(p.amount)}</td><td>{p.mode}</td><td>{p.reference||"—"}</td></tr>)}{!payments.length&&<tr><td colSpan="7">No payments recorded yet.</td></tr>}</tbody></table></div></section>}
    {view==="REPORT"&&<section className="panel"><div className="panel-head"><div><h3>Fee Collection Report</h3><p>Review billing, collections, outstanding balances and overdue invoices.</p></div><button className="primary" onClick={loadReport}>Run Report</button></div><div className="form-grid"><Select label="Academic Session" value={filters.sessionId} options={activeSessions.map(s=>[s._id,s.name])} onChange={v=>setFilters({...filters,sessionId:v})}/><Select label="Section" value={filters.sectionId} options={sectionOptions} onChange={v=>setFilters({...filters,sectionId:v})}/></div>{report&&<><div className="cards" style={{marginTop:18}}>{[["Invoices",report.summary.invoices],["Billed",money(report.summary.total)],["Collected",money(report.summary.paid)],["Outstanding",money(report.summary.balance)]].map(([n,v])=><div className="card" key={n}><div className="icon"><BarChart3/></div><div><span>{n}</span><strong>{v}</strong></div></div>)}</div><div className="message" style={{marginTop:14}}>Overdue invoices: <strong>{report.summary.overdue}</strong></div><div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>Invoice</th><th>Student</th><th>Fee Head</th><th>Net</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>{(report.invoices||[]).map(i=><tr key={i._id}><td>{i.invoiceNo}</td><td>{i.student?.rollNo} · {i.student?.name}</td><td>{i.feeHead?.name}</td><td>{money(i.netAmount)}</td><td>{money(i.paidAmount)}</td><td>{money(i.balance)}</td><td>{i.status}</td></tr>)}</tbody></table></div></>}</section>}
  </div>
}

