export const moduleRegistry={
  dashboard:{path:"/dashboard",label:"Dashboard"},
  academicSessions:{path:"/academic-sessions",label:"Academic Sessions"},
  fullSessionTimetable:{path:"/full-session-timetable",label:"Full Session Timetable"},
  allProgramTimetables:{path:"/all-program-timetables",label:"All Program Timetables"},
  timetable:{path:"/timetable",label:"Timetable"},
  calendar:{path:"/calendar",label:"Calendar View"},
  myTimetable:{path:"/my-timetable",label:"My Timetable"},
  students:{path:"/students",label:"Students"},
  studentProfile:{path:"/students/profile",label:"Student Profile"},
  studentPromotion:{path:"/students/promotion",label:"Student Promotion"},
  attendance:{path:"/attendance",label:"Attendance"},
  fees:{path:"/fees",label:"Fees"},
  facultyPortal:{path:"/faculty-portal",label:"Faculty Portal"},
  sectionPortal:{path:"/section-portal",label:"Section Portal"},
  masterData:{path:"/master-data",label:"Master Data Settings"},
  excelImport:{path:"/excel-import",label:"Excel Import"},
  templates:{path:"/templates",label:"Templates & Clone"},
  publicSharing:{path:"/public-sharing",label:"Public Sharing"},
  reports:{path:"/reports",label:"Reports"},
  analytics:{path:"/analytics",label:"Analytics"},
  notifications:{path:"/notifications",label:"Notifications"},
  changeHistory:{path:"/change-history",label:"Change History"},
  validation:{path:"/validation",label:"Validation"},
  optimization:{path:"/optimization",label:"Optimization"},
  auditLogs:{path:"/audit-logs",label:"Audit Logs"},
  users:{path:"/users",label:"User Management"},
  settings:{path:"/settings",label:"Settings"}
};
export const pathForLabel=label=>Object.values(moduleRegistry).find(x=>x.label===label)?.path||"/dashboard";
